import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, ChevronDown, ChevronRight, Heart, ListFilter, MapPin, Menu, MessageCircle, Mic, Search, ShoppingBasket, SlidersHorizontal, X } from 'lucide-react';
import catalogJson from './catalog.json';
import productsJson from './products.json';
import newsJson from './news.json';
import { api } from './api';
import { CartPage } from './CartPage';
import type { Cart } from './types';


type Category = { path: string; title: string; image: string; children: Category[] };

const categories = catalogJson as Category[];
const sampleProducts = productsJson as { path: string; image: string; title: string; sku: string }[];
const news = newsJson as { path: string; image: string; title: string; date: string }[];
const demoItemPath = sampleProducts[0].path;
const catalogRoots = [{ title: 'Спец предложение', path: '/catalog/spets_predlozhenie/' }, { title: 'Новинки', path: '/catalog/novinki/' }, ...categories.map(({ title, path }) => ({ title, path }))];
const navGroups = [
  { title: 'Группа компаний Электрокомплект', links: [['О компании', '/about/'], ['Вакансии', '/about/our-team/vacancy/'], ['Новости', '/news/'], ['Контакты', '/about/contacts/'], ['Платформа для бизнеса B2B', 'https://pro.ekt.kz/']] },
  { title: 'Будь с нами', links: [['Вход/Регистрация', '/personal/'], ['Полезная информация', '/about/information/'], ['Часто задаваемые вопросы', '/about/faq/'], ['Карьера', '/about/our-team/'], ['Сотрудничество', '/cooperation/']] },
  { title: 'Интернет магазин', links: [['Как сделать заказ?', '/about/howto/'], ['Доставка и оплата', '/checkout-delivery/'], ['Условия возврата и обмена', '/return/'], ['AirbaPay', '/payments/'], ['Условия по рассрочке', '/usloviya-po-rassrochke/']] },
];
const contentPages: Record<string, { title: string; paragraphs: string[] }> = {
  '/about/': { title: 'О компании', paragraphs: ['Группа компаний Электрокомплект — производитель и поставщик электротехнической продукции на рынке Казахстана.', 'Компания развивает производство кабельно-проводниковой продукции, труб, кабельного канала и щитового оборудования.'] },
  '/about/contacts/': { title: 'Контакты', paragraphs: ['Алматы, ул. Кудерина, 47Б', '+7 (727) 346-88-88 · +7 (778) 046-88-88'] },
  '/about/howto/': { title: 'Как сделать заказ', paragraphs: ['Выберите товары в каталоге или найдите их по артикулу. Наш помощник поможет уточнить характеристики и подготовить корзину.', 'Корзина на этой странице — часть демонстрационного прототипа. Оформление настоящего заказа доступно на ekt.kz.'] },
  '/checkout-delivery/': { title: 'Доставка и оплата', paragraphs: ['Для физических лиц на сайте ekt.kz указаны онлайн-оплата банковской картой, оплата при получении и оплата в торговом зале при самовывозе.', 'Для юридических лиц указаны оплата по счёту и оплата в торговом зале при самовывозе.', 'Стоимость и сроки доставки зависят от города и заказа. Порог бесплатной доставки и минимальную партию уточните у менеджера: публичные сведения требуют подтверждения.'] },
  '/return/': { title: 'Возврат и обмен', paragraphs: ['Условия возврата и обмена уточняйте на официальной странице ekt.kz.'] },
  '/about/faq/': { title: 'Часто задаваемые вопросы', paragraphs: ['Поиск по артикулу, помощь с аналогом и условия покупки доступны в чате помощника.'] },
  '/about/information/': { title: 'Полезная информация', paragraphs: ['Информация о товарах, заказе, оплате и доставке.'] },
  '/cooperation/': { title: 'Сотрудничество', paragraphs: ['По вопросам сотрудничества обратитесь к представителю компании.'] },
  '/payments/': { title: 'Онлайн оплата', paragraphs: ['Точные способы и условия оплаты проверяйте на официальной странице ekt.kz.'] },
  '/usloviya-po-rassrochke/': { title: 'Условия по рассрочке', paragraphs: ['Актуальные условия рассрочки проверяйте на официальной странице ekt.kz.'] },
  '/about/our-team/': { title: 'Карьера', paragraphs: ['Узнайте об актуальных вакансиях на официальном сайте.'] },
  '/about/our-team/vacancy/': { title: 'Вакансии', paragraphs: ['Узнайте об актуальных вакансиях на официальном сайте.'] },
};

function normalize(path: string) { return path.endsWith('/') ? path : path + '/'; }
function textTitle(path: string) { return decodeURIComponent(path.split('/').filter(Boolean).at(-1) || 'Каталог').replaceAll('_', ' ').replace(/\b[a-z]/g, letter => letter.toUpperCase()); }
function originalLink(path: string) { return 'https://ekt.kz' + path; }
function Breadcrumbs({ items }: { items: { title: string; path?: string }[] }) { return <nav className="breadcrumbs" aria-label="Навигация"><a href="/">Главная</a>{items.map((item, i) => <span key={i} className="crumb"><ChevronRight size={12} />{item.path ? <a href={item.path}>{item.title}</a> : <span>{item.title}</span>}</span>)}</nav>; }

function Header({ cartCount, onChat }: { cartCount: number; onChat: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [mobileSearch, setMobileSearch] = useState(false);
  const [cityOpen, setCityOpen] = useState(false);
  const [city, setCity] = useState('Алматы');
  const [query, setQuery] = useState('');
  function submitSearch(event: FormEvent) { event.preventDefault(); if (query.trim()) window.location.href = '/catalog/?q=' + encodeURIComponent(query.trim()); }
  return <>
    <div className="topbar"><div className="shell topbar-inner"><button className="city-button" onClick={() => setCityOpen(!cityOpen)}><MapPin size={17} /> {city}</button><div className="top-links"><a href="/personal/">Личный кабинет</a><a href="https://pro.ekt.kz/">B2B - EKT PRO</a><a href="/about/">Покупателям <ChevronDown size={14} /></a><a href="/about/contacts/">Оставить заявку</a><a href="https://ekt.kz/kz/">ҚАЗ</a></div><div className="phones">+7 (727) 346-88-88<br />+7 (778) 046-88-88</div></div></div>
    {cityOpen && <div className="city-popover"><strong>Ваш город: {city}</strong><p>Выберите город</p>{['Алматы', 'Астана', 'Шымкент', 'Тараз', 'Атырау', 'Актау', 'Караганда'].map(name => <button key={name} onClick={() => { setCity(name); setCityOpen(false); }}>{name}</button>)}</div>}
    <div className="main-header"><div className="shell main-header-inner"><a className="logo" href="/" aria-label="Электрокомплект — главная"><span>ГРУППА КОМПАНИЙ</span><strong>ЭЛЕКТРОКОМПЛЕКТ</strong></a><button className="catalog-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}><span>Каталог</span>{menuOpen ? <X size={20} /> : <ListFilter size={20} />}</button><form className={'search-bar' + (mobileSearch ? ' mobile-open' : '')} onSubmit={submitSearch}><Search size={21} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Поиск" aria-label="Поиск по каталогу" /><button type="submit" aria-label="Искать"><Search size={19} /></button><Mic size={18} className="search-mic" /></form><div className="header-actions"><a href="/compare/" aria-label="Сравнить"><SlidersHorizontal size={19} /><span>Сравнить</span></a><a href="/favorites/" aria-label="Избранное"><Heart size={20} /><span>Избранное</span></a><a href="/cart" aria-label="Корзина"><ShoppingBasket size={22} /><span>Корзина</span><i>{cartCount}</i></a></div><button className="mobile-search-toggle" onClick={() => setMobileSearch(!mobileSearch)} aria-label="Открыть поиск">{mobileSearch ? <X size={22} /> : <Search size={22} />}</button><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Открыть меню"><Menu size={25} /></button></div>
    {menuOpen && <div className="mega-menu shell"><div className="mega-title">Каталог продукции</div><div className="mega-grid">{catalogRoots.map(item => <a key={item.path} href={item.path}>{item.title}<ChevronRight size={15} /></a>)}</div><button onClick={onChat} className="mega-assistant"><MessageCircle size={18} /> Помощник по подбору</button></div>}</div>
  </>;
}

function CategoryGrid({ items, compact = false }: { items: Category[]; compact?: boolean }) { return <div className={compact ? 'category-grid compact' : 'category-grid'}>{items.map(item => <a className="category-tile" href={item.path} key={item.path}><img src={item.image} alt="" loading="lazy" /><span>{item.title}</span></a>)}</div>; }

function Home() { const [slide, setSlide] = useState(0); const slides = [{ image: '/assets/hero-main.png', title: 'Лотки металлические', url: '/catalog/kabelenesushchie_sistemy/' }, { image: '/assets/hero-second.png', title: 'Кабель — ГОСТ', url: '/catalog/kabel_provod/' }]; return <><section className="home-hero shell"><div className="hero-main"><a href={slides[slide].url}><img src={slides[slide].image} alt={slides[slide].title} /></a><div className="hero-dots">{slides.map((s, i) => <button key={s.title} className={slide === i ? 'active' : ''} onClick={() => setSlide(i)} aria-label={'Баннер ' + (i + 1)} />)}</div></div><a className="hero-side" href="/news/"><img src="/assets/hero-side.png" alt="Новости Электрокомплект" /></a></section><section className="home-catalog"><div className="shell"><h2><a href="/catalog/">Каталог продукции</a></h2><CategoryGrid items={categories} /></div></section><section className="home-promo shell"><div className="section-tabs"><h2>Новинки</h2><a href="/catalog/spets_predlozhenie/">Спец предложения <ArrowRight size={18} /></a></div><div className="promo-row">{categories.slice(0, 4).map(item => <a key={item.path} href={item.path}><img src={item.image} alt="" /><span>Новинки в разделе</span><strong>{item.title}</strong></a>)}</div></section><section className="about-home"><div className="shell"><h2>О компании</h2><div className="about-layout"><img src="/assets/about.jpg" alt="Группа компаний Электрокомплект" /><div><p>Группа Компаний Электрокомплект – производитель и поставщик электротехнической продукции на рынке Республики Казахстан.</p><p>Наш каталог помогает подобрать электротовары для разных задач. Помощник подскажет характеристики и подготовит демонстрационную корзину.</p><a className="outline-btn" href="/about/">Подробнее о компании <ArrowRight size={17} /></a></div></div></div></section><section className="news-home shell"><h2><a href="/news/">Узнать больше</a></h2><div className="news-row">{news.slice(0, 3).map(article => <a href={article.path} key={article.path}><img src={article.image} alt="" /><div className="news-date">{article.date}</div><strong>{article.title}</strong></a>)}</div></section></>; }

function CatalogPage({ path }: { path: string }) {
  const query = new URLSearchParams(window.location.search).get('q')?.trim() || '';
  const root = categories.find(item => path.startsWith(item.path));
  const exact = categories.find(item => item.path === path);
  const child = root?.children.find(item => item.path === path);
  const productListing = path.includes('/acti_9_6_63_a_schneider_electric/');
  const title = query ? 'Результаты поиска' : path === '/catalog/' ? 'Каталог' : exact?.title || child?.title || (path === '/catalog/novinki/' ? 'Новинки' : path === '/catalog/spets_predlozhenie/' ? 'Спец предложение' : textTitle(path));
  const shown = query ? categories.flatMap(item => [item, ...item.children]).filter(item => item.title.toLowerCase().includes(query.toLowerCase())) : path === '/catalog/' ? categories : exact?.children.length ? exact.children : root?.children.length ? root.children : categories.slice(0, 8);
  const productsToShow = query ? sampleProducts.filter(item => (item.title + ' ' + item.sku).toLowerCase().includes(query.toLowerCase())) : sampleProducts;
  const showProducts = productListing || path.includes('/modulnye_avtomaticheskie_vyklyuchateli/') || productsToShow.length > 0 && Boolean(query);
  return <main className="catalog-page shell"><h1>{title}</h1><Breadcrumbs items={path === '/catalog/' ? [{ title }] : [{ title: 'Каталог', path: '/catalog/' }, ...(root && root.path !== path ? [{ title: root.title, path: root.path }] : []), { title }]} />{query && <p className="result-note">По запросу «{query}» показаны разделы локального прототипа. Для проверки артикула откройте помощника.</p>}<div className={'catalog-layout' + (path === '/catalog/' ? ' root-only' : '')}>{path !== '/catalog/' && <aside className="filters"><strong>Фильтр по параметрам</strong><label><input type="checkbox" /> В наличии</label>{['Категория', 'Новинка', 'Спецпредложение', 'Производитель', 'Номинальный ток', 'Степень защиты IP'].map(item => <details key={item}><summary>{item}</summary><div className="filter-inner"><label><input type="checkbox" /> Да</label><label><input type="checkbox" /> Нет</label></div></details>)}<button className="filter-apply">Показать результат</button></aside>}<div className="catalog-content">{path !== '/catalog/' && <div className="sort-row"><span>{showProducts ? productsToShow.length + ' товаров' : shown.length + ' разделов'}</span><button>Сортировать <ChevronDown size={15} /></button><SlidersHorizontal size={22} /></div>}{showProducts ? <><p className="result-note">Образцы карточек из публичного каталога. Цена и наличие уточняются при запросе.</p><div className="product-grid">{productsToShow.map(product => <a className="product-tile" href={product.path} key={product.path}><span className="product-brand">Schneider<br />Electric</span><img src={product.image} alt="" loading="lazy" /><strong>{product.title}</strong><span className="product-price-label">цена на сайте</span><b>Уточняется</b><small>Код товара {product.sku}</small><span className="product-tile-action">Подробнее <ArrowRight size={15} /></span></a>)}</div></> : shown.length ? <>{child && <p className="result-note">Другие разделы категории. Полный ассортимент смотрите на официальном сайте.</p>}<CategoryGrid items={shown} compact={path !== '/catalog/'} /></> : <div className="empty-block">Разделы по запросу не найдены. Попробуйте другой запрос или спросите помощника.</div>}{path !== '/catalog/' && !showProducts && <div className="featured-product"><h2>Пример карточки товара</h2><div><img src="/assets/product.jpg" alt="Автоматический выключатель" /><section><span className="eyebrow">Образец страницы · данные требуют проверки</span><h3>Авт. Выкл. C120N C 80A 3P Schneider Electric</h3><p>Артикул A9N18365</p><p>Цена и наличие уточняются через каталог.</p><a className="outline-btn" href={demoItemPath}>Посмотреть карточку <ArrowRight size={17} /></a></section></div></div>}</div></div></main>;
}

function ProductPage({ product }: { product: (typeof sampleProducts)[number] }) { const [tab, setTab] = useState<'description' | 'features'>('description'); return <main className="product-page shell"><h1>{product.title}</h1><Breadcrumbs items={[{ title: 'Каталог', path: '/catalog/' }, { title: 'Низковольтная аппаратура', path: categories[2].path }, { title: 'Автоматические выключатели', path: categories[2].children[0].path }, { title: product.sku }]} /><div className="product-layout"><div className="product-image"><img src={product.image} alt={product.title} /></div><div className="product-info"><div className="product-fav"><span><Heart size={20} /> Избранное</span><span><SlidersHorizontal size={20} /> Сравнить</span></div><div className="price-row"><div><span>Цена на сайте</span><strong>Уточняется</strong></div><div><span>Наличие</span><strong>Уточняется</strong></div></div><p className="demo-warning">Это визуальный прототип. Актуальные цену и остаток проверьте у помощника или на ekt.kz.</p><button className="yellow-btn" onClick={() => window.dispatchEvent(new Event('open-assistant'))}><MessageCircle size={19} /> Уточнить у помощника</button><a className="outline-btn" href={originalLink(product.path)} target="_blank" rel="noreferrer">Открыть на ekt.kz <ArrowRight size={16} /></a><div className="delivery-card"><ShoppingBasket size={22} /><div><strong>Оплата и доставка</strong><p>Условия покупки зависят от вашего заказа и города.</p><a href="/checkout-delivery/">Подробнее <ArrowRight size={15} /></a></div></div></div></div><div className="product-tabs"><div><button onClick={() => setTab('description')} className={tab === 'description' ? 'active' : ''}>Описание</button><button onClick={() => setTab('features')} className={tab === 'features' ? 'active' : ''}>Характеристики</button></div>{tab === 'description' ? <p>Подробные характеристики и совместимость уточняйте по артикулу в каталоге.</p> : <dl><dt>Артикул</dt><dd>{product.sku}</dd><dt>Категория</dt><dd>Модульные автоматические выключатели</dd></dl>}</div></main>; }

function InfoPage({ path }: { path: string }) { const page = contentPages[path] || { title: textTitle(path), paragraphs: ['Информация этого раздела доступна на официальном сайте Электрокомплект.'] }; return <main className="info-page shell"><h1>{page.title}</h1><Breadcrumbs items={[{ title: page.title }]} /><article className="generic-article">{page.paragraphs.map((p, i) => <p key={i}>{p}</p>)}<a className="outline-btn" href={originalLink(path)} target="_blank" rel="noreferrer">Проверить на ekt.kz <ArrowRight size={17} /></a></article></main>; }

function FAQPage() { const entries = [
  ['Как связаться с EKT для консультации?', 'Откройте страницу контактов или позвоните по телефону, указанному в шапке сайта.'],
  ['Можно ли вернуть или обменять товар?', 'Условия зависят от товара и обстоятельств покупки. Проверьте официальные правила возврата и свяжитесь с магазином.'],
  ['Какие документы нужны представителю юридического лица для получения товара?', 'Перечень документов уточните у менеджера перед получением заказа.'],
  ['Как быстро доставляется заказ?', 'Срок зависит от региона, наличия товара и согласования заказа с менеджером.'],
  ['Сколько стоит доставка?', 'Стоимость зависит от заказа и адреса. Публичные сведения о пороге бесплатной доставки требуют уточнения у менеджера.'],
]; return <main className="info-page shell"><h1>Часто задаваемые вопросы (FAQ)</h1><Breadcrumbs items={[{ title: 'О компании', path: '/about/' }, { title: 'Часто задаваемые вопросы (FAQ)' }]} /><div className="faq-list">{entries.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={20} /></summary><p>{answer}</p></details>)}</div></main>; }

function NewsPage() { return <main className="info-page shell"><h1>Новости</h1><Breadcrumbs items={[{ title: 'Новости' }]} /><div className="news-grid">{news.map(article => <a href={article.path} key={article.path}><img src={article.image} alt="" loading="lazy" /><div><span>{article.date}</span><h3>{article.title}</h3></div></a>)}</div></main>; }

function NewsArticle({ article }: { article: (typeof news)[number] }) { return <main className="info-page shell"><h1>{article.title}</h1><Breadcrumbs items={[{ title: 'Новости', path: '/news/' }, { title: article.title }]} /><article className="news-article"><img src={article.image} alt="" /><span>{article.date}</span><h2>{article.title}</h2><p>Материал представлен в визуальном прототипе. Полный и актуальный текст читайте на официальном сайте.</p><a className="outline-btn" href={originalLink(article.path)} target="_blank" rel="noreferrer">Читать на ekt.kz <ArrowRight size={16} /></a></article></main>; }

function AboutPage() { const panels = [{ title: 'Производство', image: '/assets/about-production.png', text: 'Кабельно-проводниковая продукция, щитовое оборудование, трубы и кабельный канал.' }, { title: 'Наши клиенты', image: '/assets/about-clients.png', text: 'Долгосрочное сотрудничество с клиентами по всему Казахстану.' }, { title: 'Наши преимущества', image: '/assets/about-benefits.jpg', text: 'Развитие собственного производства и широкого ассортимента.' }, { title: 'Партнёры', image: '/assets/about-partners.png', text: 'Сотрудничество с производителями электротехники.' }]; return <main className="info-page shell"><h1>О компании</h1><Breadcrumbs items={[{ title: 'О компании' }]} /><div className="about-panels">{panels.map(panel => <section key={panel.title} style={{ backgroundImage: `linear-gradient(90deg,#18344890,transparent),url(${panel.image})` }}><h2>{panel.title}</h2><p>{panel.text}</p></section>)}</div></main>; }

function DeliveryPage() { return <main className="info-page shell"><h1>Условия доставки и оплаты</h1><Breadcrumbs items={[{ title: 'Условия доставки и оплаты' }]} /><article className="delivery-article"><h2>Оплата</h2><p>При оформлении покупки на физическое лицо доступны:</p><ul><li>оплата банковской картой онлайн на сайте;</li><li>оплата при получении товара;</li><li>оплата в торговом зале компании при самовывозе.</li></ul><p>При оформлении покупки на юридическое лицо после получения счёта доступны:</p><ul><li>оплата перечислением на счёт компании;</li><li>оплата в торговом зале компании при самовывозе.</li></ul><h2>Доставка</h2><p>Условия доставки зависят от города и параметров заказа. Стоимость и сроки доставки в другие города согласовываются с менеджером.</p><p className="result-note">Публичные сведения о пороге бесплатной доставки расходятся; условие минимальной партии не подтверждено. Уточните эти условия у менеджера.</p><a className="outline-btn" href="https://ekt.kz/checkout-delivery/" target="_blank" rel="noreferrer">Актуальные условия на ekt.kz <ArrowRight size={16} /></a></article></main>; }

function ContactsPage() { const [city, setCity] = useState('Алматы'); return <main className="info-page shell"><h1>Контакты</h1><Breadcrumbs items={[{ title: 'О компании', path: '/about/' }, { title: 'Контакты' }]} /><article className="contacts-article"><h2>Выберите город:</h2><select aria-label="Выберите город" value={city} onChange={event => setCity(event.target.value)}>{['Алматы', 'Астана', 'Шымкент', 'Тараз', 'Атырау', 'Актау', 'Караганда', 'Талдыкорган', 'Усть-Каменогорск'].map(value => <option key={value}>{value}</option>)}</select>{city === 'Алматы' ? <div className="contact-details"><h3>Подразделение в г. Алматы</h3><small>Заходите в гости</small><p>050061, Республика Казахстан, г. Алматы, ул. Кудерина, 47Б</p><small>Звоните нам</small><p><a href="tel:+77273468888">+7 (727) 346-88-88</a><br /><a href="tel:+77780468888">+7 (778) 046-88-88</a></p><small>Пишите нам</small><p><a href="mailto:almaty@ekt.kz">almaty@ekt.kz</a></p><small>График работы</small><p>Пн–Пт, 09:00–18:00</p></div> : <div className="contact-details"><h3>{city}</h3><p>Актуальные адрес и контакты подразделения проверьте на официальном сайте.</p><a className="outline-btn" href="https://ekt.kz/about/contacts/" target="_blank" rel="noreferrer">Контакты на ekt.kz <ArrowRight size={16} /></a></div>}</article></main>; }

function HowtoPage() { const steps = [{ title: 'Подбор товара', text: 'Найдите нужный раздел каталога или воспользуйтесь поиском по названию и артикулу.' }, { title: 'Проверка заказа', text: 'Уточните характеристики, остаток и условия покупки. Помощник подготовит предложение перед изменением демонстрационной корзины.' }, { title: 'Подтверждение', text: 'После отдельного подтверждения корзина прототипа обновится. Для оформления реального заказа перейдите на ekt.kz.' }]; return <main className="info-page shell"><h1>Как сделать заказ</h1><Breadcrumbs items={[{ title: 'О компании', path: '/about/' }, { title: 'Как сделать заказ' }]} /><div className="howto-steps">{steps.map((step, i) => <section key={step.title}><div className="step-number">{i + 1}</div><h2>{step.title}</h2><p>{step.text}</p></section>)}<a className="outline-btn" href="https://ekt.kz/about/howto/" target="_blank" rel="noreferrer">Инструкция на ekt.kz <ArrowRight size={16} /></a></div></main>; }

function ReturnPage() { return <main className="info-page shell"><h1>Условия возврата и обмена</h1><Breadcrumbs items={[{ title: 'Условия возврата и обмена' }]} /><article className="delivery-article return-article"><h2>Условия возврата/обмена товаров</h2><p>Порядок возврата зависит от товара, его состояния и документов о покупке. Перед возвратом свяжитесь с представителем магазина и проверьте актуальные правила.</p><h2>Подробная информация</h2><p>Полный перечень условий и ограничений опубликован на официальной странице компании.</p><a className="outline-btn" href="https://ekt.kz/return/" target="_blank" rel="noreferrer">Проверить на ekt.kz <ArrowRight size={16} /></a></article></main>; }

function PersonalPage() { return <main className="info-page shell"><h1>Авторизация</h1><Breadcrumbs items={[{ title: 'Профиль пользователя' }]} /><article className="personal-form"><h2>Пожалуйста, авторизуйтесь</h2><p className="result-note">Вход в аккаунт доступен только на официальном сайте. Поля здесь показаны для воспроизведения дизайна.</p><label>E-mail<input type="email" disabled /></label><label>Пароль<input type="password" disabled /></label><label className="remember"><input type="checkbox" disabled /> Запомнить меня на этом компьютере</label><a className="login-link" href="https://ekt.kz/personal/" target="_blank" rel="noreferrer">Войти на ekt.kz <ArrowRight size={16} /></a><hr /><a href="https://ekt.kz/personal/" target="_blank" rel="noreferrer">Забыли свой пароль?</a><p>Если вы впервые на сайте, заполните, пожалуйста, регистрационную форму.</p><a href="https://ekt.kz/personal/" target="_blank" rel="noreferrer">Зарегистрироваться</a></article></main>; }

function SmallPage({ type }: { type: 'favorites' | 'compare' }) { const title = type === 'favorites' ? 'Избранное' : 'Сравнение товаров'; return <main className="info-page shell small-page"><h1>{title}</h1><Breadcrumbs items={[{ title }]} />{type === 'favorites' ? <><div className="favorites-tab">Избранное</div><p>В вашем избранном пусто</p></> : <><p>Список сравниваемых товаров пуст</p><p>Для сравнения товаров поставьте галочку «Сравнить» на двух или более товарах.</p><a className="yellow-btn" href="/catalog/">В каталог</a></>}</main>; }

function Footer({ onChat }: { onChat: () => void }) { return <><section className="newsletter"><div className="shell"><div><strong>Подписаться на рассылку</strong><span>Новости и полезная информация</span></div><form onSubmit={event => event.preventDefault()}><input type="email" placeholder="Введите ваш e-mail" aria-label="Email" /><button type="submit">Подписаться</button></form></div></section><footer className="site-footer"><div className="shell footer-columns">{navGroups.map(group => <div key={group.title}><h3>{group.title}</h3>{group.links.map(([name, href]) => <a href={href} key={href}>{name}</a>)}</div>)}<div><h3>Каталог продукции</h3>{categories.slice(0, 6).map(item => <a href={item.path} key={item.path}>{item.title}</a>)}<button onClick={onChat}>Помощник по подбору</button></div></div><div className="shell footer-bottom"><span>© Группа компаний Электрокомплект · Визуальный прототип для HackAlem AI</span><a href="https://ekt.kz/" target="_blank" rel="noreferrer">Официальный сайт ekt.kz</a></div></footer></>; }

function App() { const [cartCount, setCartCount] = useState(0); const path = normalize(window.location.pathname); const product = sampleProducts.find(item => item.path === path);  let content; if (path === '/') content = <Home />; else if (path === '/cart/' || path === '/personal/cart/') content = <CartPage />; else if (path === '/favorites/') content = <SmallPage type="favorites" />; else if (path === '/compare/') content = <SmallPage type="compare" />; else if (path === '/personal/') content = <PersonalPage />; else if (path === '/news/') content = <NewsPage />; else if (path === '/about/') content = <AboutPage />; else if (path === '/about/contacts/') content = <ContactsPage />; else if (path === '/about/faq/') content = <FAQPage />; else if (path === '/about/howto/') content = <HowtoPage />; else if (path === '/checkout-delivery/') content = <DeliveryPage />; else if (path === '/return/') content = <ReturnPage />; else if (news.find(item => item.path === path)) content = <NewsArticle article={news.find(item => item.path === path)!} />; else if (product) content = <ProductPage product={product} />; else if (path.startsWith('/catalog/')) content = <CatalogPage path={path} />; else content = <InfoPage path={path} />; useEffect(() => { const update = (event: Event) => setCartCount((event as CustomEvent<Cart>).detail.itemCount); window.addEventListener('ekt-cart-snapshot', update); api.cart().then(cart => setCartCount(cart.itemCount)).catch(() => {}); return () => window.removeEventListener('ekt-cart-snapshot', update); }, []); return <><Header cartCount={cartCount} onChat={() => window.dispatchEvent(new Event('open-assistant'))} />{content}<Footer onChat={() => window.dispatchEvent(new Event('open-assistant'))} /></>; }

export default App;
